### ISSUE TITLE
Support uploading kubeconfig on the host as well as via http url

### ISSUE THREAD

**Issue by chaitanyaenr** [krkn-chaos/krkn-dashboard#9]
Adding support for the user to upload the url from the host as well as being able to provide a url with the kubeconfig accessible over http will make it easy for multiple users to run tests without having to access the host on which the dashboard server is running.

**Comment by chaitanyaenr** [comment]
@MVarshini thoughts?

**Comment by MVarshini** [comment]
> @MVarshini thoughts?

Sure, Ravi!
